


server:
  port: 8010

spring:
  application:
    name: bulkheadservice
  config.import: optional:configserver:http://localhost:8050

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}



resilience4j:
  bulkhead:
    instances:
      getMessageBH:
        max-concurrent-calls: 5 # indicates that if the number of concurrent calls exceed 5, activate the fallback method.
        max-wait-duration: 0 #indicates that don’t wait for anything, show response immediately based on the configuration.