server:
  port: 8083

spring:
  application:
    name: microservice-3
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0


logging:
  file:
    name: C:/Users/mitea/Desktop/basic-microservice/zpkin-project/myLogs/serviceThree.log